/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpoedRouteImport } from './routes/spoed'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProthesesRouteImport } from './routes/protheses'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BehandelingenRouteImport } from './routes/behandelingen'
import { Route as AfspraakRouteImport } from './routes/afspraak'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SpoedRoute = SpoedRouteImport.update({
  id: '/spoed',
  path: '/spoed',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProthesesRoute = ProthesesRouteImport.update({
  id: '/protheses',
  path: '/protheses',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BehandelingenRoute = BehandelingenRouteImport.update({
  id: '/behandelingen',
  path: '/behandelingen',
  getParentRoute: () => rootRouteImport,
} as any)
const AfspraakRoute = AfspraakRouteImport.update({
  id: '/afspraak',
  path: '/afspraak',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afspraak': typeof AfspraakRoute
  '/behandelingen': typeof BehandelingenRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/over-ons': typeof OverOnsRoute
  '/protheses': typeof ProthesesRoute
  '/reviews': typeof ReviewsRoute
  '/spoed': typeof SpoedRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afspraak': typeof AfspraakRoute
  '/behandelingen': typeof BehandelingenRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/over-ons': typeof OverOnsRoute
  '/protheses': typeof ProthesesRoute
  '/reviews': typeof ReviewsRoute
  '/spoed': typeof SpoedRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/afspraak': typeof AfspraakRoute
  '/behandelingen': typeof BehandelingenRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/over-ons': typeof OverOnsRoute
  '/protheses': typeof ProthesesRoute
  '/reviews': typeof ReviewsRoute
  '/spoed': typeof SpoedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/afspraak'
    | '/behandelingen'
    | '/contact'
    | '/login'
    | '/over-ons'
    | '/protheses'
    | '/reviews'
    | '/spoed'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/afspraak'
    | '/behandelingen'
    | '/contact'
    | '/login'
    | '/over-ons'
    | '/protheses'
    | '/reviews'
    | '/spoed'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/afspraak'
    | '/behandelingen'
    | '/contact'
    | '/login'
    | '/over-ons'
    | '/protheses'
    | '/reviews'
    | '/spoed'
    | '/_authenticated/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AfspraakRoute: typeof AfspraakRoute
  BehandelingenRoute: typeof BehandelingenRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  OverOnsRoute: typeof OverOnsRoute
  ProthesesRoute: typeof ProthesesRoute
  ReviewsRoute: typeof ReviewsRoute
  SpoedRoute: typeof SpoedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spoed': {
      id: '/spoed'
      path: '/spoed'
      fullPath: '/spoed'
      preLoaderRoute: typeof SpoedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protheses': {
      id: '/protheses'
      path: '/protheses'
      fullPath: '/protheses'
      preLoaderRoute: typeof ProthesesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behandelingen': {
      id: '/behandelingen'
      path: '/behandelingen'
      fullPath: '/behandelingen'
      preLoaderRoute: typeof BehandelingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afspraak': {
      id: '/afspraak'
      path: '/afspraak'
      fullPath: '/afspraak'
      preLoaderRoute: typeof AfspraakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AfspraakRoute: AfspraakRoute,
  BehandelingenRoute: BehandelingenRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  OverOnsRoute: OverOnsRoute,
  ProthesesRoute: ProthesesRoute,
  ReviewsRoute: ReviewsRoute,
  SpoedRoute: SpoedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
