/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WortelkanaalbehandelingRouteImport } from './routes/wortelkanaalbehandeling'
import { Route as SpoedRouteImport } from './routes/spoed'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProthesesRouteImport } from './routes/protheses'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KindertandheelkundeRouteImport } from './routes/kindertandheelkunde'
import { Route as ImplantologieRouteImport } from './routes/implantologie'
import { Route as GeneralDentalCareRouteImport } from './routes/general-dental-care'
import { Route as EsthetischeTandheelkundeRouteImport } from './routes/esthetische-tandheelkunde'
import { Route as DeclaratiesRouteImport } from './routes/declaraties'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BehandelingenRouteImport } from './routes/behandelingen'
import { Route as AfspraakRouteImport } from './routes/afspraak'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const WortelkanaalbehandelingRoute = WortelkanaalbehandelingRouteImport.update({
  id: '/wortelkanaalbehandeling',
  path: '/wortelkanaalbehandeling',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoedRoute = SpoedRouteImport.update({
  id: '/spoed',
  path: '/spoed',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProthesesRoute = ProthesesRouteImport.update({
  id: '/protheses',
  path: '/protheses',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KindertandheelkundeRoute = KindertandheelkundeRouteImport.update({
  id: '/kindertandheelkunde',
  path: '/kindertandheelkunde',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantologieRoute = ImplantologieRouteImport.update({
  id: '/implantologie',
  path: '/implantologie',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralDentalCareRoute = GeneralDentalCareRouteImport.update({
  id: '/general-dental-care',
  path: '/general-dental-care',
  getParentRoute: () => rootRouteImport,
} as any)
const EsthetischeTandheelkundeRoute =
  EsthetischeTandheelkundeRouteImport.update({
    id: '/esthetische-tandheelkunde',
    path: '/esthetische-tandheelkunde',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeclaratiesRoute = DeclaratiesRouteImport.update({
  id: '/declaraties',
  path: '/declaraties',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BehandelingenRoute = BehandelingenRouteImport.update({
  id: '/behandelingen',
  path: '/behandelingen',
  getParentRoute: () => rootRouteImport,
} as any)
const AfspraakRoute = AfspraakRouteImport.update({
  id: '/afspraak',
  path: '/afspraak',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afspraak': typeof AfspraakRoute
  '/behandelingen': typeof BehandelingenRoute
  '/contact': typeof ContactRoute
  '/declaraties': typeof DeclaratiesRoute
  '/esthetische-tandheelkunde': typeof EsthetischeTandheelkundeRoute
  '/general-dental-care': typeof GeneralDentalCareRoute
  '/implantologie': typeof ImplantologieRoute
  '/kindertandheelkunde': typeof KindertandheelkundeRoute
  '/login': typeof LoginRoute
  '/over-ons': typeof OverOnsRoute
  '/protheses': typeof ProthesesRoute
  '/reviews': typeof ReviewsRoute
  '/spoed': typeof SpoedRoute
  '/wortelkanaalbehandeling': typeof WortelkanaalbehandelingRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afspraak': typeof AfspraakRoute
  '/behandelingen': typeof BehandelingenRoute
  '/contact': typeof ContactRoute
  '/declaraties': typeof DeclaratiesRoute
  '/esthetische-tandheelkunde': typeof EsthetischeTandheelkundeRoute
  '/general-dental-care': typeof GeneralDentalCareRoute
  '/implantologie': typeof ImplantologieRoute
  '/kindertandheelkunde': typeof KindertandheelkundeRoute
  '/login': typeof LoginRoute
  '/over-ons': typeof OverOnsRoute
  '/protheses': typeof ProthesesRoute
  '/reviews': typeof ReviewsRoute
  '/spoed': typeof SpoedRoute
  '/wortelkanaalbehandeling': typeof WortelkanaalbehandelingRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/afspraak': typeof AfspraakRoute
  '/behandelingen': typeof BehandelingenRoute
  '/contact': typeof ContactRoute
  '/declaraties': typeof DeclaratiesRoute
  '/esthetische-tandheelkunde': typeof EsthetischeTandheelkundeRoute
  '/general-dental-care': typeof GeneralDentalCareRoute
  '/implantologie': typeof ImplantologieRoute
  '/kindertandheelkunde': typeof KindertandheelkundeRoute
  '/login': typeof LoginRoute
  '/over-ons': typeof OverOnsRoute
  '/protheses': typeof ProthesesRoute
  '/reviews': typeof ReviewsRoute
  '/spoed': typeof SpoedRoute
  '/wortelkanaalbehandeling': typeof WortelkanaalbehandelingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/afspraak'
    | '/behandelingen'
    | '/contact'
    | '/declaraties'
    | '/esthetische-tandheelkunde'
    | '/general-dental-care'
    | '/implantologie'
    | '/kindertandheelkunde'
    | '/login'
    | '/over-ons'
    | '/protheses'
    | '/reviews'
    | '/spoed'
    | '/wortelkanaalbehandeling'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/afspraak'
    | '/behandelingen'
    | '/contact'
    | '/declaraties'
    | '/esthetische-tandheelkunde'
    | '/general-dental-care'
    | '/implantologie'
    | '/kindertandheelkunde'
    | '/login'
    | '/over-ons'
    | '/protheses'
    | '/reviews'
    | '/spoed'
    | '/wortelkanaalbehandeling'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/afspraak'
    | '/behandelingen'
    | '/contact'
    | '/declaraties'
    | '/esthetische-tandheelkunde'
    | '/general-dental-care'
    | '/implantologie'
    | '/kindertandheelkunde'
    | '/login'
    | '/over-ons'
    | '/protheses'
    | '/reviews'
    | '/spoed'
    | '/wortelkanaalbehandeling'
    | '/_authenticated/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AfspraakRoute: typeof AfspraakRoute
  BehandelingenRoute: typeof BehandelingenRoute
  ContactRoute: typeof ContactRoute
  DeclaratiesRoute: typeof DeclaratiesRoute
  EsthetischeTandheelkundeRoute: typeof EsthetischeTandheelkundeRoute
  GeneralDentalCareRoute: typeof GeneralDentalCareRoute
  ImplantologieRoute: typeof ImplantologieRoute
  KindertandheelkundeRoute: typeof KindertandheelkundeRoute
  LoginRoute: typeof LoginRoute
  OverOnsRoute: typeof OverOnsRoute
  ProthesesRoute: typeof ProthesesRoute
  ReviewsRoute: typeof ReviewsRoute
  SpoedRoute: typeof SpoedRoute
  WortelkanaalbehandelingRoute: typeof WortelkanaalbehandelingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wortelkanaalbehandeling': {
      id: '/wortelkanaalbehandeling'
      path: '/wortelkanaalbehandeling'
      fullPath: '/wortelkanaalbehandeling'
      preLoaderRoute: typeof WortelkanaalbehandelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoed': {
      id: '/spoed'
      path: '/spoed'
      fullPath: '/spoed'
      preLoaderRoute: typeof SpoedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protheses': {
      id: '/protheses'
      path: '/protheses'
      fullPath: '/protheses'
      preLoaderRoute: typeof ProthesesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kindertandheelkunde': {
      id: '/kindertandheelkunde'
      path: '/kindertandheelkunde'
      fullPath: '/kindertandheelkunde'
      preLoaderRoute: typeof KindertandheelkundeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implantologie': {
      id: '/implantologie'
      path: '/implantologie'
      fullPath: '/implantologie'
      preLoaderRoute: typeof ImplantologieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general-dental-care': {
      id: '/general-dental-care'
      path: '/general-dental-care'
      fullPath: '/general-dental-care'
      preLoaderRoute: typeof GeneralDentalCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esthetische-tandheelkunde': {
      id: '/esthetische-tandheelkunde'
      path: '/esthetische-tandheelkunde'
      fullPath: '/esthetische-tandheelkunde'
      preLoaderRoute: typeof EsthetischeTandheelkundeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/declaraties': {
      id: '/declaraties'
      path: '/declaraties'
      fullPath: '/declaraties'
      preLoaderRoute: typeof DeclaratiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behandelingen': {
      id: '/behandelingen'
      path: '/behandelingen'
      fullPath: '/behandelingen'
      preLoaderRoute: typeof BehandelingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afspraak': {
      id: '/afspraak'
      path: '/afspraak'
      fullPath: '/afspraak'
      preLoaderRoute: typeof AfspraakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AfspraakRoute: AfspraakRoute,
  BehandelingenRoute: BehandelingenRoute,
  ContactRoute: ContactRoute,
  DeclaratiesRoute: DeclaratiesRoute,
  EsthetischeTandheelkundeRoute: EsthetischeTandheelkundeRoute,
  GeneralDentalCareRoute: GeneralDentalCareRoute,
  ImplantologieRoute: ImplantologieRoute,
  KindertandheelkundeRoute: KindertandheelkundeRoute,
  LoginRoute: LoginRoute,
  OverOnsRoute: OverOnsRoute,
  ProthesesRoute: ProthesesRoute,
  ReviewsRoute: ReviewsRoute,
  SpoedRoute: SpoedRoute,
  WortelkanaalbehandelingRoute: WortelkanaalbehandelingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
